### ISSUE TITLE
I can't find capistrano-git-copy-bundle in rubygem.org.

### ISSUE THREAD

**Issue by hiroyuki-sato** [ydkn/capistrano-git-copy-bundle#1]
Hello

From this issue.

[Is it possible to execute "bundle cache" command in git cloned directory? #11](https://github.com/ydkn/capistrano-git-copy/issues/11)

I can't find capistrano-git-copy-bundle in rubygem.org.

https://rubygems.org/search?utf8=✓&query=capistrano-git-copy-bundle

I would be very happy if you could possibly tell me how to do it.

Thanks.

**Comment by ydkn** [comment]
Just released it:
https://rubygems.org/gems/capistrano-git-copy-bundle

**Comment by hiroyuki-sato** [comment]
Thanks!!
